services:
  postgres:
    image: 'postgres:16.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ReflexProjectManagementCore
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - 5432:5432