spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ReflexProjectManagementCore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true